### PR TITLE
fix directory structure

### PR DESCRIPTION
**Pull request by Sovamorco**

### CODE REVIEW

**Review by Alllais — COMMENTED** [review]
Thank you for clarifying, I was under the same misunderstanding

**Comment by Sovamorco** [comment]
Doesn't pass the linter, but nothing will for now. That would have to be a separate PR fixing a bunch of inconsistencies

**Review by Alllais — COMMENTED** [review]
If you're cleaning up directories, please also remove routers

**Comment by Sovamorco** [comment]
> If you're cleaning up directories, please also remove routers

Done

**Review by Alllais — APPROVED** [review]

**Pull request merged**
